### ISSUE TITLE
Civchat died on startup, again. 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/CivChat2#10]
2015-05-23 08:26:37 [ERROR] Error occurred while enabling CivChat2 v1.0.3 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: 1
        at vg.civcraft.mc.civchat2.CivChat2Manager.loadIgnoredPlayers(CivChat2Manager.java:519) ~[?:?]
        at vg.civcraft.mc.civchat2.zipper.CivChat2FileLogger.initIgnoreLog(CivChat2FileLogger.java:124) ~[?:?]
        at vg.civcraft.mc.civchat2.zipper.CivChat2FileLogger.Init(CivChat2FileLogger.java:64) ~[?:?]
        at vg.civcraft.mc.civchat2.CivChat2.onEnable(CivChat2.java:45) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by ttk2** [comment]
this happened on the first startup, but not again on the second.

**Comment by jjj5311** [comment]
Weird....

I can't look at it now and will be intermittent internet access for the
next week while traveling I'll try To figure it out if I get some spare
time

**Comment by ttk2** [comment]
well it needs to get fixed before the next restart really. Going to hand it off to someone else then.

**Comment by rourke750** [comment]
@jjj5311 What is the point of this line https://github.com/Civcraft/CivChat2/blob/master/src/vg/civcraft/mc/civchat2/CivChat2Manager.java#L517 ?

**Comment by jjj5311** [comment]
Ummm....  I think it was to skip the first line. Seems to not make sense to
me now though

**Comment by idoash4** [comment]
Can one of the admins go over the ignorelist file and check if there is a line with only one name in it?

**Comment by rourke750** [comment]
https://github.com/Civcraft/CivChat2/commit/6f23b9d15ee5787f012a657f3d7a857c87517e43

**Comment by rourke750** [comment]
@jjj5311 That should do it right?

**Comment by jjj5311** [comment]
Yeahithinkthatshouldfixit

**Comment by ttk2** [comment]
updated on civtest.
