### ISSUE TITLE
Error occurred while enabling CivChat2 v1.0.3 (Is it up to date?) java.lang.NoClassDefFoundError: vg/civcraft/mc/namelayer/command/Command on Civtest

### ISSUE THREAD

**Issue by ttk2** [Civcraft/CivChat2#24]
2015-07-02 22:27:22 [INFO] [CivChat2] [Debug] Debug Enabled
2015-07-02 22:27:22 [ERROR] Error occurred while enabling CivChat2 v1.0.3 (Is it up to date?)
java.lang.NoClassDefFoundError: vg/civcraft/mc/namelayer/command/Command
        at vg.civcraft.mc.civchat2.CivChat2.onEnable(CivChat2.java:49) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.ClassNotFoundException: vg.civcraft.mc.namelayer.command.Command
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_45-internal]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45-internal]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45-internal]
        ... 12 more

**Comment by jjj5311** [comment]
That looks like the version from the live server? It shouldn't be using
namelayer command

**Comment by ttk2** [comment]
what version should I be using on Civtest?

**Comment by jjj5311** [comment]
this can be closed?

**Comment by ttk2** [comment]
Yes it can.
