### ISSUE TITLE
stack on startup. 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/CivChat2#3]
2015-05-16 18:13:56 [ERROR] Error occurred while enabling CivChat2 v1.0.1 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: 1
        at vg.civcraft.mc.civchat2.CivChat2Manager.loadIgnoredPlayers(CivChat2Manager.java:514) ~[?:?]
        at vg.civcraft.mc.civchat2.zipper.CivChat2FileLogger.initIgnoreLog(CivChat2FileLogger.java:124) ~[?:?]
        at vg.civcraft.mc.civchat2.zipper.CivChat2FileLogger.Init(CivChat2FileLogger.java:64) ~[?:?]
        at vg.civcraft.mc.civchat2.CivChat2.onEnable(CivChat2.java:45) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:200) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by rourke750** [comment]
@jjj5311

**Comment by jjj5311** [comment]
Can you enable debugging in the config and post the startup again? Also if there is an ignore log saved can you tell me what's in it

**Comment by ttk2** [comment]
this only happened once and not again during subsequent restarts, might
have been somthing strange.

**Comment by jjj5311** [comment]
Was this stack for the initial startup? if so it was caused by the old format of the ignore file... so this should not be a problem anymore

**Comment by ttk2** [comment]
Probably the old ignore format.

**Comment by jjj5311** [comment]
This can be closed since it was the old format causing the error
