### ISSUE TITLE
Could not pass event PlayerChangeServerEvent to CivChat2  (when pearling a player on one server to be sent to another)

### ISSUE THREAD

**Issue by ttk2** [Civcraft/CivChat2#45]
2016-01-09 18:20:35 [ERROR] Could not pass event PlayerChangeServerEvent to CivChat2 v1.2                                                                             [395/9013]
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-d97e08b-880a532]
        at vg.civcraft.mc.bettershards.BetterShardsPlugin.teleportPlayerToServer(BetterShardsPlugin.java:161) [BetterShards-1.3.35.jar:?]
        at vg.civcraft.mc.bettershards.BetterShardsAPI.connectPlayer(BetterShardsAPI.java:25) [BetterShards-1.3.35.jar:?]
        at com.untamedears.PrisonPearl.PrisonPearlPlugin.getRespawnLocation(PrisonPearlPlugin.java:642) [PrisonPearl-2.7.22.jar:?]
        at com.untamedears.PrisonPearl.PrisonPearlPlugin.onPlayerRespawn(PrisonPearlPlugin.java:616) [PrisonPearl-2.7.22.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72-internal]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72-internal]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:568) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:507) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1393) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInClientCommand.a(SourceFile:31) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInClientCommand.a(SourceFile:8) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.namelayer.database.AssociationList.getCurrentName(AssociationList.java:124) ~[?:?]
        at vg.civcraft.mc.namelayer.NameAPI.getCurrentName(NameAPI.java:64) ~[?:?]
        at vg.civcraft.mc.civchat2.listeners.BetterShardsListener.PlayerChangeServer(BetterShardsListener.java:29) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72-internal]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72-internal]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-d97e08b-880a532]

**Comment by Maxopoly** [comment]
That stack isn't civchat related

**Comment by ProgrammerDan** [comment]
Yes it is: https://github.com/Civcraft/CivChat2/blob/master/src/vg/civcraft/mc/civchat2/listeners/BetterShardsListener.java#L26

**Comment by ProgrammerDan** [comment]
> Caused by: java.lang.NullPointerException
> at vg.civcraft.mc.namelayer.database.AssociationList.getCurrentName(AssociationList.java:124) ~[?:?]
> at vg.civcraft.mc.namelayer.NameAPI.getCurrentName(NameAPI.java:64) ~[?:?]
> at vg.civcraft.mc.civchat2.listeners.BetterShardsListener.PlayerChangeServer(BetterShardsListener.java:29) ~[?:?]

**Comment by Maxopoly** [comment]
Oh that was an old issue where null was being passed as uuid to resolve. Fixed that months ago. Aside from that there is not a single line in the stack linking to civchat, so I dont think there's anything to do here.

**Comment by ProgrammerDan** [comment]
I pasted the lines that impact CivChat. They are at the bottom, as usual in Java stack traces. This NPE was originated in CivChat.

Fix is easy: https://github.com/Civcraft/CivChat2/blob/master/src/vg/civcraft/mc/civchat2/listeners/BetterShardsListener.java#L27

Just check if `event.getPlayerUUID()` is null _before_ sending the request to NameAPI.

Ah, good though if upstream is fixed; however adding the check I advise here would be good practice to prevent regressions in the future.

**Comment by Maxopoly** [comment]
It would never be null though. I'm not sure how exactly this stack was created, but it's definitely no longer happening and if the uuid of a player was null, the whole thing would first fail in a lot of other places.

**Comment by ProgrammerDan** [comment]
I edited probably after you read:

> Ah, good though if upstream is fixed; however adding the check I advise here would be good practice to prevent regressions in the future.

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/CivChat2/commit/df225b5b07cfeff2a4fdbff69034e475f0177080
