### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to CivChat2 v1.0.1

### ISSUE THREAD

**Issue by ttk2** [Civcraft/CivChat2#5]
2015-05-16 18:39:27 [ERROR] Could not pass event AsyncPlayerChatEvent to CivChat2 v1.0.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.chat(PlayerConnection.java:1061) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:999) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45-internal]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
        at com.mysql.jdbc.ResultSetImpl.buildIndexMapping(ResultSetImpl.java:754) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1108) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5616) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at vg.civcraft.mc.namelayer.database.AssociationList.getUUID(AssociationList.java:105) ~[?:?]
        at vg.civcraft.mc.namelayer.NameAPI.getUUID(NameAPI.java:24) ~[?:?]
        at vg.civcraft.mc.civchat2.CivChat2Manager.broadcastMessage(CivChat2Manager.java:222) ~[?:?]
        at vg.civcraft.mc.civchat2.listeners.CivChat2Listener.PlayerChatEvent(CivChat2Listener.java:102) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor153.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        ... 11 more

**Comment by jjj5311** [comment]
Do we know who tried to do the chat? looks like it wasnt able to look up their UUID from their bukkit player name?  @rourke750  is there something wrong with the way i try to get that info?

https://github.com/Civcraft/CivChat2/blob/master/src/vg/civcraft/mc/civchat2/CivChat2Manager.java#L222

**Comment by rourke750** [comment]
If you do Bukkit.getPlayer() it returns null if the player is not online.
Use NameLayer for all name stuff.  Otherwise you can do
Bukkit.getofflineplayer() if you need to get other stuff.

**Comment by jjj5311** [comment]
I'm using name layer to get uuid and it's getting null

**Comment by rourke750** [comment]
Try removing the startup tag.

**Comment by jjj5311** [comment]
what do you mean?

**Comment by rourke750** [comment]
https://github.com/Civcraft/CivChat2/blob/master/plugin.yml#L4

You don't need that line.  I don't think.  Are you modifying anything before the load worlds?

**Comment by jjj5311** [comment]
Nope we can try it for sure

**Comment by jjj5311** [comment]
This is no longer occurring right?

**Comment by ttk2** [comment]
2015-05-22 18:04:11 [INFO] [CivChat2] [Debug] PlayerChatEvent occured
2015-05-22 18:04:11 [INFO] [CivChat2] [Debug] PlayerChatEvent occured
2015-05-22 18:04:11 [INFO] [CivChat2] [Debug] getChannel returning null
2015-05-22 18:04:11 [INFO] [CivChat2] [Debug] getChannel returning null
2015-05-22 18:04:11 [INFO] [CivChat2] [Debug] Checking if user is
groupchatting name=[HyperxKing]
2015-05-22 18:04:11 [INFO] [CivChat2] [Debug] Checking if user is
groupchatting name=[HyperxKing]
2015-05-22 18:04:11 [INFO] [CivChat2] [Debug] ChatEvent properties:
chatMessage =[ Im from haven ], sender = [ PLAYERNAMEREDACTED ],
chatChannel = [ null ], groupchatting = [ null ];
2015-05-22 18:04:11 [INFO] [CivChat2] [Debug] ChatEvent properties:
chatMessage =[ howdy ], sender = [ PLAYERNAMEREDACTED ], chatChannel = [
null ], groupchatting = [ null ];
2015-05-22 18:04:11 [INFO] [CivChat2] [Debug] PlayerChatEvent calling
chatman.broadcastMessage()
2015-05-22 18:04:11 [INFO] [CivChat2] [Debug] PlayerChatEvent calling
chatman.broadcastMessage()
2015-05-22 18:04:11 [ERROR] Could not pass event AsyncPlayerChatEvent to
CivChat2 v1.0.3
org.bukkit.event.EventException
        at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305)
~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.PlayerConnection.chat(PlayerConnection.java:1061)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:999)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[?:1.8.0_45-internal]
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[?:1.8.0_45-internal]
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[?:1.8.0_45-internal]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException

**Comment by erocs** [comment]
Just saw an instance of this in the log from a few minutes ago.

**Comment by jjj5311** [comment]
This one has me stumped... Was the player spamming chat? I do not understand why there are two instances of all the debugging info and it the null pointer does not seem to be within civchat

**Comment by ttk2** [comment]
It is possible it was a failure in bukkit.

**Comment by suirad** [comment]
See above commit

**Comment by suirad** [comment]
See above pull

**Comment by suirad** [comment]
Please close
