### ISSUE TITLE
NPE at CivChat2Manager.sendGroupMsg

### ISSUE THREAD

**Issue by erocs** [Civcraft/CivChat2#6]
2015-05-17 12:55:00 [INFO] ABC issued server command: /groupchat def hi
2015-05-17 12:55:00 [INFO] [CivChat2] [Debug] chatMan = [vg.civcraft.mc.civchat2.CivChat2Manager@3c0d84c2]
2015-05-17 12:55:00 [INFO] [CivChat2] [Debug] checking if name=[ABC] is groupchatting
2015-05-17 12:55:00 [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'groupchat' in plugin CivChat2 v1.0.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.civchat2.CivChat2Manager.sendGroupMsg(CivChat2Manager.java:440) ~[?:?]
        at vg.civcraft.mc.civchat2.command.commands.GroupChat.execute(GroupChat.java:119) ~[?:?]
        at vg.civcraft.mc.civchat2.command.CivChat2CommandHandler.execute(CivChat2CommandHandler.java:43) ~[?:?]
        at vg.civcraft.mc.civchat2.CivChat2.onCommand(CivChat2.java:82) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        ... 15 more

**Comment by jjj5311** [comment]
is this occuring all the time?

**Comment by jjj5311** [comment]
@ttk2 i believe this is fixed can admin confirm?

**Comment by ttk2** [comment]
looks good.
